# numpy

In [1]:
num1= int(input("enter two numnbers:"))
num2= int(input("enter two numnbers:"))

enter two numnbers:4
enter two numnbers:5


In [3]:
print(f"addition:{num1+num2}")

addition:9


In [4]:
print(f"multiplication:{num1*num2}")


multiplication:20


In [11]:
prev=0
for i  in range(10):
    s=prev+i
    
    print(s)
    prev = i



0
1
3
5
7
9
11
13
15
17


In [13]:
s = "pynative"
print(s[::2])

pntv


In [15]:
def remove_char(word,n):
    x = word[n :]
    return x

print(remove_char("pynative",4))

tive


In [17]:
# Using a list in Python to add 5 to each number
numbers = [1, 2, 3, 4, 5]
for x in numbers:
    result = x + 5 
    print(result)  # Output: [6, 7, 8, 9, 10]


6
7
8
9
10


In [19]:
import numpy as np
list1 = [1,2,3,4,5]
list2 = [2,3,4,5,6]
list3 = [9,7,6,8,9]
arr = np.array([list1,list2,list3])

In [20]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [21]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [29]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [32]:
arr.shape

(3, 5)

In [34]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [37]:
a = np.arange(0,10,step=5)
a

array([0, 5])

In [38]:
s = np.linspace(0,10,50)

In [39]:
s

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [53]:

np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [57]:
import random
np.random.rand(3,10)

array([[0.20863148, 0.18108932, 0.35972516, 0.60060534, 0.93774404,
        0.86910195, 0.46011233, 0.94748229, 0.30575855, 0.30747937],
       [0.6516049 , 0.56586672, 0.61275258, 0.42329936, 0.8450411 ,
        0.8010482 , 0.01549766, 0.92184272, 0.19724334, 0.77997618],
       [0.65339611, 0.44277983, 0.4759389 , 0.02208923, 0.81621032,
        0.83666628, 0.44437246, 0.82303471, 0.81284991, 0.99002498]])